/* RanniStats push notifications — Cloudflare Worker.
 *
 * The website itself stays where it is, on GitHub Pages. This Worker is a
 * separate small API that does the two things a static file can't:
 *
 *   1. remembers which devices want which alerts (KV, keyed by the push
 *      endpoint — there are no accounts and no user ids anywhere in here);
 *   2. wakes up on a cron schedule, asks ESPN what changed since last time,
 *      and pushes the differences to the devices that asked for them.
 *
 * Design notes worth knowing before changing anything:
 *
 *   - The VAPID keypair is generated by the Worker on first use and kept in
 *     KV. That means no private key is ever pasted into a terminal, mailed
 *     around, or stored in a repo. The cost is one lazily-initialised value.
 *
 *   - "What changed" is computed by diffing against the previous poll, stored
 *     in KV. ESPN has no change feed, so the previous scoreboard IS the state.
 *     A scoring play is a score that moved while a game is in progress; a
 *     final is a game whose state became "post". This means a missed cron run
 *     collapses two plays into one notification rather than sending a stale
 *     pair — the right tradeoff for a lock screen.
 *
 *   - Every push is best-effort. Push services return 404/410 for
 *     subscriptions that no longer exist (app deleted, browser data cleared),
 *     and that is the ONLY signal we ever get that a device is gone, so those
 *     responses prune the record. Everything else is logged and ignored.
 */

import { generateKeyPair, sendPush, bytesToB64url } from "./webpush.js";

const MAX_SUBS = 2000;          // a sanity cap; this is a personal-scale app
/* KV's list() rejects a limit above 1000. MAX_SUBS was being passed straight
 * in, so every list call threw -- silently, because the only caller that
 * mattered was inside a waitUntil with no catch. Page with the cursor instead,
 * so the cap stays a cap rather than a hidden ceiling. */
const KV_LIST_MAX = 1000;
async function listKeys(kv, prefix, max){
  const out = [];
  let cursor;
  do {
    const page = await kv.list({ prefix: prefix, limit: Math.min(KV_LIST_MAX, max - out.length), cursor: cursor });
    out.push.apply(out, page.keys || []);
    cursor = page.list_complete ? null : page.cursor;
  } while (cursor && out.length < max);
  return out;
}
const MAX_BODY = 4096;          // bytes of JSON we'll accept on a POST
const NEWS_MEMORY = 120;        // article ids remembered, to detect "new"
const SCOREBOARD = "https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard";
const NEWS = "https://site.api.espn.com/apis/site/v2/sports/football/nfl/news?limit=30";
const INJURY_WORDS = /\b(injur\w*|placed on IR|out for|surger\w*|questionable|doubtful|hamstring|concussion|sidelined|torn \w+|fractured?|sprain\w*|ruled out)\b/i;

/* ---- helpers ------------------------------------------------------------ */

function corsHeaders(request, env) {
  const allowed = (env.ALLOWED_ORIGINS || "").split(",").map(s => s.trim()).filter(Boolean);
  const origin = request.headers.get("Origin") || "";
  // Only echo an origin we were configured for. A wildcard here would let any
  // page on the internet drive this API from a visitor's browser.
  const ok = allowed.includes(origin);
  return {
    "Access-Control-Allow-Origin": ok ? origin : allowed[0] || "null",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Max-Age": "86400",
    Vary: "Origin",
  };
}
const json = (data, request, env, status = 200) =>
  new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json", ...corsHeaders(request, env) },
  });

async function readJson(request) {
  const text = await request.text();
  if (text.length > MAX_BODY) throw new Error("body too large");
  return JSON.parse(text);
}

async function endpointKey(endpoint) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(endpoint));
  return "sub:" + bytesToB64url(new Uint8Array(digest)).slice(0, 32);
}

/* The keypair the push services use to recognise us. Generated here on first
 * call so it never has to travel through a person. */
async function getVapid(env) {
  const stored = await env.PUSH_KV.get("vapid", "json");
  if (stored) return stored;
  const kp = await generateKeyPair("sign");
  const vapid = {
    publicKey: bytesToB64url(kp.publicKey),
    privateKeyJwk: kp.privateKeyJwk,
    subject: env.VAPID_SUBJECT || "mailto:admin@example.com",
  };
  await env.PUSH_KV.put("vapid", JSON.stringify(vapid));
  // Re-read so that if two cold starts raced, everyone converges on the
  // value that actually landed rather than the one this instance made.
  return (await env.PUSH_KV.get("vapid", "json")) || vapid;
}

function validSubscription(s) {
  return !!(s && typeof s.endpoint === "string" &&
    /^https:\/\//.test(s.endpoint) && s.endpoint.length < 1024 &&
    s.keys && typeof s.keys.p256dh === "string" && typeof s.keys.auth === "string");
}
function cleanTeams(list) {
  if (!Array.isArray(list)) return [];
  return list.filter(t => typeof t === "string" && /^[A-Z]{2,3}$/.test(t)).slice(0, 32);
}
function cleanTriggers(t) {
  t = t || {};
  return { finals: !!t.finals, plays: !!t.plays, injuries: !!t.injuries };
}

/* ---- HTTP -------------------------------------------------------------- */

async function handleRequest(request, env) {
  const url = new URL(request.url);
  if (request.method === "OPTIONS") return new Response(null, { headers: corsHeaders(request, env) });

  // The page needs the public key before it can call subscribe().
  if (url.pathname === "/key" && request.method === "GET") {
    const vapid = await getVapid(env);
    return json({ publicKey: vapid.publicKey }, request, env);
  }

  if (url.pathname === "/subscribe" && request.method === "POST") {
    let body;
    try { body = await readJson(request); } catch { return json({ error: "bad request" }, request, env, 400); }
    if (!validSubscription(body.subscription)) return json({ error: "bad subscription" }, request, env, 400);

    const key = await endpointKey(body.subscription.endpoint);
    const existing = await env.PUSH_KV.get(key, "json");
    if (!existing) {
      const keys = await listKeys(env.PUSH_KV, "sub:", MAX_SUBS + 1);
      if (keys.length > MAX_SUBS) return json({ error: "at capacity" }, request, env, 503);
    }
    await env.PUSH_KV.put(key, JSON.stringify({
      subscription: body.subscription,
      teams: cleanTeams(body.teams),
      triggers: cleanTriggers(body.triggers),
      updatedAt: Date.now(),
      createdAt: existing ? existing.createdAt : Date.now(),
    }));
    return json({ ok: true }, request, env);
  }

  if (url.pathname === "/unsubscribe" && request.method === "POST") {
    let body;
    try { body = await readJson(request); } catch { return json({ error: "bad request" }, request, env, 400); }
    if (typeof body.endpoint !== "string") return json({ error: "bad request" }, request, env, 400);
    await env.PUSH_KV.delete(await endpointKey(body.endpoint));
    return json({ ok: true }, request, env);
  }

  // Lets the app's "send me a test" button prove the whole chain end to end.
  if (url.pathname === "/test" && request.method === "POST") {
    let body;
    try { body = await readJson(request); } catch { return json({ error: "bad request" }, request, env, 400); }
    const rec = await env.PUSH_KV.get(await endpointKey(body.endpoint || ""), "json");
    if (!rec) return json({ error: "not subscribed" }, request, env, 404);
    const vapid = await getVapid(env);
    const res = await sendPush(rec.subscription, {
      title: "RanniStats notifications are on",
      body: "This is what an alert will look like.",
      tag: "rannistats-test",
      url: "./index.html",
    }, vapid);
    if (res.gone) await env.PUSH_KV.delete(await endpointKey(body.endpoint));
    return json({ ok: res.ok, status: res.status }, request, env, res.ok ? 200 : 502);
  }

  // A tiny status page, so "is this thing alive?" doesn't need the dashboard.
  if (url.pathname === "/" || url.pathname === "/status") {
    const keys = await listKeys(env.PUSH_KV, "sub:", MAX_SUBS);
    const lastRun = await env.PUSH_KV.get("state:lastRun");
    return json({
      ok: true,
      subscriptions: keys.length,
      lastCronRun: lastRun ? new Date(Number(lastRun)).toISOString() : null,
    }, request, env);
  }

  return json({ error: "not found" }, request, env, 404);
}

/* ---- the poller -------------------------------------------------------- */

// 6 and 7 both read as a touchdown to a person; the extra point is not news.
function describeScoringPlay(delta) {
  if (delta >= 6) return "touchdown";
  if (delta === 3) return "field goal";
  if (delta === 2) return "safety";
  if (delta === 1) return "extra point";
  return "score";
}

export function diffScoreboard(events, previous) {
  const next = {};
  const notifications = [];
  for (const ev of events || []) {
    const comp = ev.competitions && ev.competitions[0];
    if (!comp) continue;
    const home = (comp.competitors || []).find(c => c.homeAway === "home");
    const away = (comp.competitors || []).find(c => c.homeAway === "away");
    if (!home || !away) continue;
    // ESPN reports status on both the event and the competition and they can
    // disagree during a transition; prefer the competition, fall back to the
    // event rather than silently treating a live game as "pre".
    const status = (comp.status && comp.status.type) || (ev.status && ev.status.type) || {};
    const state = status.state || "pre";
    const cur = {
      h: home.team.abbreviation, a: away.team.abbreviation,
      hs: Number(home.score) || 0, as: Number(away.score) || 0,
      state,
      detail: status.shortDetail || status.description || "",
    };
    next[ev.id] = cur;
    const prev = previous && previous[ev.id];
    if (!prev) continue; // first time we've seen this game: record, don't shout

    const line = cur.a + " " + cur.as + " – " + cur.h + " " + cur.hs;

    if (state === "post" && prev.state !== "post") {
      const winner = cur.hs === cur.as ? null : (cur.hs > cur.as ? cur.h : cur.a);
      notifications.push({
        kind: "final",
        teams: [cur.h, cur.a],
        title: winner ? winner + " win, " + line : "Final: " + line,
        body: cur.detail || "Final",
        tag: "final-" + ev.id,
      });
    } else if (state === "in") {
      const dh = cur.hs - prev.hs, da = cur.as - prev.as;
      if (dh > 0 || da > 0) {
        const scorer = dh >= da ? cur.h : cur.a;
        const delta = Math.max(dh, da);
        notifications.push({
          kind: "play",
          teams: [cur.h, cur.a],
          title: scorer + " " + describeScoringPlay(delta),
          body: line + " · " + (cur.detail || "in progress"),
          // One tag per game, so a stream of plays replaces itself on the
          // lock screen instead of stacking into a wall.
          tag: "play-" + ev.id,
          urgency: "high",
        });
      }
    }
  }
  return { next, notifications };
}

export function diffNews(articles, seenIds) {
  const seen = new Set(seenIds || []);
  const notifications = [];
  const ids = [];
  for (const a of articles || []) {
    const id = String(a.id || a.headline || "");
    if (!id) continue;
    ids.push(id);
    if (seen.has(id)) continue;
    const text = (a.headline || "") + " " + (a.description || "");
    if (!INJURY_WORDS.test(text)) continue;
    const teamCat = (a.categories || []).find(c => c.type === "team" && c.team && c.team.abbreviation);
    if (!teamCat) continue; // team-specific alerts only; league-wide isn't "your team"
    const abbr = teamCat.team.abbreviation === "WSH" ? "WAS" : teamCat.team.abbreviation;
    notifications.push({
      kind: "injury",
      teams: [abbr],
      title: abbr + " injury news",
      body: a.headline,
      tag: "injury-" + id,
      url: (a.links && a.links.web && a.links.web.href) || null,
    });
  }
  // Remember the ids we just saw, newest first, capped. On the very first run
  // seenIds is empty, so nothing is sent — otherwise turning the feature on
  // would fire thirty backdated injury alerts at once.
  return { notifications, ids: ids.slice(0, NEWS_MEMORY) };
}

function wants(record, note) {
  const t = record.triggers || {};
  if (note.kind === "final" && !t.finals) return false;
  if (note.kind === "play" && !t.plays) return false;
  if (note.kind === "injury" && !t.injuries) return false;
  const teams = record.teams || [];
  return note.teams.some(x => teams.includes(x));
}

export async function runPoll(env, deps = {}) {
  const fetchImpl = deps.fetch || fetch;
  const push = deps.sendPush || sendPush;

  const keys = await listKeys(env.PUSH_KV, "sub:", MAX_SUBS);
  await env.PUSH_KV.put("state:lastRun", String(Date.now()));
  if (!keys.length) return { skipped: "no subscribers" };

  const records = [];
  for (const k of keys) {
    const rec = await env.PUSH_KV.get(k.name, "json");
    if (rec) records.push({ key: k.name, ...rec });
  }
  const anyPlays = records.some(r => r.triggers && r.triggers.plays);
  const anyFinals = records.some(r => r.triggers && r.triggers.finals);
  const anyInjuries = records.some(r => r.triggers && r.triggers.injuries);

  const notifications = [];

  if (anyPlays || anyFinals) {
    try {
      const sb = await fetchImpl(SCOREBOARD).then(r => r.json());
      const prev = await env.PUSH_KV.get("state:scores", "json");
      const { next, notifications: scoreNotes } = diffScoreboard(sb.events, prev);
      await env.PUSH_KV.put("state:scores", JSON.stringify(next));
      notifications.push(...scoreNotes);
    } catch (e) {
      console.log("scoreboard poll failed:", e && e.message);
    }
  }

  if (anyInjuries) {
    try {
      const nw = await fetchImpl(NEWS).then(r => r.json());
      const seen = await env.PUSH_KV.get("state:newsSeen", "json");
      const first = !seen;
      const { notifications: newsNotes, ids } = diffNews(nw.articles, seen || (nw.articles || []).map(a => String(a.id)));
      await env.PUSH_KV.put("state:newsSeen", JSON.stringify(ids));
      if (!first) notifications.push(...newsNotes);
    } catch (e) {
      console.log("news poll failed:", e && e.message);
    }
  }

  if (!notifications.length) return { sent: 0, notifications: 0 };

  const vapid = await getVapid(env);
  let sent = 0, pruned = 0, failed = 0;
  for (const rec of records) {
    for (const note of notifications) {
      if (!wants(rec, note)) continue;
      try {
        const res = await push(rec.subscription, {
          title: note.title, body: note.body, tag: note.tag,
          url: note.url || "./index.html", urgency: note.urgency || "normal",
        }, vapid, fetchImpl);
        if (res.gone) { await env.PUSH_KV.delete(rec.key); pruned++; break; }
        if (res.ok) sent++; else failed++;
      } catch (e) {
        failed++;
        console.log("push failed:", e && e.message);
      }
    }
  }
  return { sent, pruned, failed, notifications: notifications.length };
}

export default {
  async fetch(request, env) {
    try {
      return await handleRequest(request, env);
    } catch (e) {
      console.log("unhandled:", e && e.stack);
      return json({ error: "server error" }, request, env, 500);
    }
  },
  async scheduled(event, env, ctx) {
    // A rejection inside waitUntil is otherwise swallowed whole: the cron looks
    // like it simply never ran, with nothing in the log saying why. That is
    // exactly how a bad KV list limit hid here.
    ctx.waitUntil(
      runPoll(env)
        .then(r => console.log("poll:", JSON.stringify(r)))
        .catch(e => console.log("poll FAILED:", (e && e.stack) || e))
    );
  },
};
